"use client";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "An aesthetic room is given harmony",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const isEHomeRoute = pathname === "/e-home";

  return (
    <html lang="en">
      <body className={inter.className}>
        {!isEHomeRoute && <Header />}
        {children}
        {!isEHomeRoute && <Footer />}
      </body>
    </html>
  );
}
