import "./globals.css";
import AppLayout from "@/components/AppLayout";

export const metadata = {
  title: "An aesthetic room is given harmony",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="vsc-initialized">
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
