import "./globals.css";
import AppLayout from "@/components/AppLayout";
import Script from "next/script";

export const metadata = {
  title: "An aesthetic room is given harmony",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="vsc-initialized">
        {/* Chatbot script added here */}
        <Script
          src="https://unihox-zenith-chatbot-u-rjlx6.ondigitalocean.app/static/chatbot-widget.js"
          strategy="afterInteractive"
        />
        <AppLayout>{children}</AppLayout>

        {/* Chatbot script added here */}
        <Script
          src="https://unihox-zenith-chatbot-u-rjlx6.ondigitalocean.app/static/chatbot-widget.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
